language: ruby
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - jruby-19mode
notifications:
  email:
    - lucas.renan@codeminer42.com
    - dmitry.rocha@codeminer42.com
    - rafael.belo@codeminer42.com
